--demo用
insert into tb_member(pwd,name,email,gender,mphoto,point) values('12345678','畢卡索','picaso@gmail.com',1,'/memberPhoto/picaso.jpg',1200)
insert into tb_member(pwd,name,email,gender,mphoto) values('12345678','達文西','bbb@gmail.com',1,'/memberPhoto/mengnalisa.jpeg')
insert into tb_member(pwd,name,email,gender,mphoto) values('12345678','維梅爾','ccc@gmail.com',1,'/memberPhoto/weimeier.JPG')
insert into tb_member(pwd,name,email,gender,mphoto) values('12345678','梵谷','ddd@gmail.com',1,'/memberPhoto/vangogh.jpg')
insert into tb_member(pwd,name,email,gender,mphoto,point) values('12345678','孟克','teiulin0914@outlook.com',1,'/memberPhoto/user.png',500)

insert into tb_favorite(mid,tag,fcount) values(5,'女',1000);
insert into tb_favorite(mid,tag,fcount) values(5,'日本',1100);


--預設相簿
insert into tb_album(aname,mid,wid) values('default',1,1);
insert into tb_album(aname,mid,wid) values('default',2,2);
insert into tb_album(aname,mid,wid) values('default',3,3);
insert into tb_album(aname,mid,wid) values('default',4,4);
--insert into tb_album(aname,mid,wid) values('default',5,5);

--作品&Tag
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart,isscore,score_1,score_2,score_3,score_4,scoreversion) values(1,'/img/1/this_thing_called_art_is_really_dangerous_by_agnes_cecile-d5ax6g0.jpg','菸癮','煙霧吞吐間的，<br />一種思緒。',123,0,1,'2017-01-01',1,'用色','線條張力','主題性','意境',1)
insert into tb_tag(wid,tag,lock) values(1,'香菸',1)
insert into tb_tag(wid,tag) values(1,'水彩')
insert into tb_tag(wid,tag) values(1,'女')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(2,'/img/2/ebb-and-flow-mandy-budan.jpg','田間','小路',5,1,2,'2017-01-02')
insert into tb_tag(wid,tag) values(2,'鄉村')
insert into tb_tag(wid,tag) values(2,'藍天')
insert into tb_tag(wid,tag) values(2,'大樹')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(3,'/img/3/cartoon-bang-2.jpg','BANG','美漫',444,1,3,'2017-01-03')
insert into tb_tag(wid,tag) values(3,'美式')
insert into tb_tag(wid,tag) values(3,'漫畫')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(4,'/img/4/Art-and-Design1.jpg','藝術人像','',55,1,4,'2017-01-04')
insert into tb_tag(wid,tag) values(4,'照片')
insert into tb_tag(wid,tag) values(4,'抽象')
insert into tb_tag(wid,tag) values(4,'拼湊')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(1,'/img/5/66c296763667635ea6388fbcf3038704.jpg','大眼','水汪汪',99,1,1,'2017-01-05')
insert into tb_tag(wid,tag) values(5,'眼睛')
insert into tb_tag(wid,tag) values(5,'色彩')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(1,'/img/1/BrugeillesNoahsArk.jpg','方舟','滿載而歸。',123,1,1,'2017-03-17')
insert into tb_tag(wid,tag) values(6,'動物')
insert into tb_tag(wid,tag) values(6,'船')
insert into tb_tag(wid,tag) values(6,'大樹')
insert into tb_tag(wid,tag) values(6,'交通工具')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(2,'/img/2/0a82578d14d85631344a96082fef1fed.jpg','魚缸','想要變成金魚，<br />也許鑽進魚缸會有用？',5,1,2,'2017-03-17')
insert into tb_tag(wid,tag) values(7,'動物')
insert into tb_tag(wid,tag) values(7,'水')
insert into tb_tag(wid,tag) values(7,'女')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(3,'/img/3/smash_n__splash_2_by_jisuart-da1j5lc.jpg','沙灘排球','卡通明星打亂鬥！<br />童年呀。',444,1,3,'2017-03-16')
insert into tb_tag(wid,tag) values(8,'藍天')
insert into tb_tag(wid,tag) values(8,'漫畫')
insert into tb_tag(wid,tag) values(8,'寶可夢')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(4,'/img/4/bright-idea.jpg','新點子','夕陽',55,1,4,'2017-03-18')
insert into tb_tag(wid,tag) values(9,'光點')
insert into tb_tag(wid,tag) values(9,'太陽')
insert into tb_tag(wid,tag) values(9,'照片')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(1,'/img/5/timthumb.jpg','綠意','山林',99,1,1,'2017-03-20')
insert into tb_tag(wid,tag) values(10,'山')
insert into tb_tag(wid,tag) values(10,'水彩')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(1,'/img/1/megan-duncanson.jpg','樹蔭','樹葉間隙，<br />灑落的星光。',99,1,1,'2017-03-20')
insert into tb_tag(wid,tag) values(11,'大樹')
insert into tb_tag(wid,tag) values(11,'夢幻')
insert into tb_tag(wid,tag) values(11,'光點')

insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(1,'/img/1/113d411212e47747d.jpg','下沉','漂浮',123,2,1,'2017-06-10')
insert into tb_tag(wid,tag) values(12,'女')
insert into tb_tag(wid,tag) values(12,'水彩')
insert into tb_tag(wid,tag) values(12,'長髮')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(2,'/img/2/4633a3eb19863a6abf8e0ae8a6812389.jpg','山麓','綿延。',5,2,2,'2017-06-10')
insert into tb_tag(wid,tag) values(13,'鄉村')
insert into tb_tag(wid,tag) values(13,'荒野')
insert into tb_tag(wid,tag) values(13,'石頭')
insert into tb_tag(wid,tag) values(13,'山')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(3,'/img/3/stuartdavis.jpg','無題','',4444,2,3,'2017-06-10')
insert into tb_tag(wid,tag) values(14,'塗鴉')
insert into tb_tag(wid,tag) values(14,'抽象')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(4,'/img/4/soap-bubble-1958841_960_720.jpg','玻璃珠','',55,2,4,'2017-06-10')
insert into tb_tag(wid,tag) values(15,'意境')
insert into tb_tag(wid,tag) values(15,'照片')
insert into tb_tag(wid,tag) values(15,'夢幻')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(1,'/img/5/622raivq4apkz2t55t9daqem.jpg','戰士','疲憊',99,2,1,'2017-06-10')
insert into tb_tag(wid,tag) values(16,'油畫')
insert into tb_tag(wid,tag) values(16,'勇士')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(1,'/img/1/Cat-in-Window-Painting-HOME.jpg','貓','我家主子的油畫試寫，<br />哈哈!',1263,2,1,'2017-06-10')
insert into tb_tag(wid,tag) values(17,'動物')
insert into tb_tag(wid,tag) values(17,'可愛')
insert into tb_tag(wid,tag) values(17,'毛茸茸')
insert into tb_tag(wid,tag) values(17,'油畫')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(2,'/img/2/Zoom1.jpg','樹屋','大樹上的豪宅，<br />小心別墜落。',5,2,2,'2017-06-10')
insert into tb_tag(wid,tag) values(18,'大樹')
insert into tb_tag(wid,tag) values(18,'蜿蜒')
insert into tb_tag(wid,tag) values(18,'房屋')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(3,'/img/3/Shohei-Otomo.jpg','不良','看屁!',444,2,3,'2017-06-10')
insert into tb_tag(wid,tag) values(19,'日本')
insert into tb_tag(wid,tag) values(19,'女')
insert into tb_tag(wid,tag) values(19,'文化')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(4,'/img/4/img_67920257.jpg','流水','森林溪流，綠意。',515,2,4,'2017-06-10')
insert into tb_tag(wid,tag) values(20,'大樹')
insert into tb_tag(wid,tag) values(20,'水')
insert into tb_tag(wid,tag) values(20,'照片')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(1,'/img/5/pollockTateModern.gif','無題','潑灑',919,2,1,'2017-06-10')
insert into tb_tag(wid,tag) values(21,'水彩')
insert into tb_tag(wid,tag) values(21,'抽象')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid,wstart) values(2,'/img/2/nnmbtdG.jpg','水箭龜','童年x浮世繪',99,2,2,'2017-06-10')
insert into tb_tag(wid,tag) values(22,'寶可夢')
insert into tb_tag(wid,tag) values(22,'神奇寶貝')
insert into tb_tag(wid,tag) values(22,'水')
insert into tb_tag(wid,tag) values(22,'日本')

insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid) values(1,'/img/1/9d7bf0bc196a6fa0402b7cb1a27c35a3.jpg','女子','色彩繽紛!',123,1,1)
insert into tb_tag(wid,tag) values(23,'女')
insert into tb_tag(wid,tag) values(23,'水彩')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid) values(2,'/img/2/image-728739_960_720.jpg','小汽車','童年',5555,0,2)
insert into tb_tag(wid,tag) values(24,'汽車')
insert into tb_tag(wid,tag) values(24,'玩具')
insert into tb_tag(wid,tag) values(24,'交通工具')
insert into tb_tag(wid,tag) values(24,'排列')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid) values(3,'/img/3/japanese-manga-3.jpg','愛麗絲','夢遊仙境',444,0,3)
insert into tb_tag(wid,tag) values(25,'漫畫')
insert into tb_tag(wid,tag) values(25,'女')
insert into tb_tag(wid,tag) values(25,'日本')
insert into tb_tag(wid,tag) values(25,'萌')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid) values(4,'/img/4/GettyImages-651237888-1024x683.jpg','廢墟','殘破的文明',5,0,4)
insert into tb_tag(wid,tag) values(26,'汽車')
insert into tb_tag(wid,tag) values(26,'照片')
insert into tb_tag(wid,tag) values(26,'photo')
insert into tb_tag(wid,tag) values(26,'破舊')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid) values(1,'/img/5/Student_LIfe_Art_MS_LION.jpg','萬獸之王','',99,0,1)
insert into tb_tag(wid,tag) values(27,'動物')
insert into tb_tag(wid,tag) values(27,'色彩')
insert into tb_tag(wid,tag) values(27,'毛茸茸')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid) values(1,'/img/1/painting-desktop-wallpaper-15.jpg','夕陽','是夕陽，<br />亦或是朝日。',123,0,1)
insert into tb_tag(wid,tag) values(28,'光點')
insert into tb_tag(wid,tag) values(28,'太陽')
insert into tb_tag(wid,tag) values(28,'大樹')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid) values(2,'/img/2/OpHrsSacFemBox.jpg','閉眼','什麼也不看。',5,0,2)
insert into tb_tag(wid,tag) values(29,'女')
insert into tb_tag(wid,tag) values(29,'塗鴉')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid) values(3,'/img/3/419831_27639_619626_KX3K.jpg','華麗','',444,0,3)
insert into tb_tag(wid,tag) values(30,'漫畫')
insert into tb_tag(wid,tag) values(30,'萌')
insert into tb_tag(wid,tag) values(30,'寶石')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid) values(4,'/img/4/27391.jpg','快樂','燦爛笑容',55,0,4)
insert into tb_tag(wid,tag) values(31,'照片')
insert into tb_tag(wid,tag) values(31,'女')
insert into tb_tag(wid,tag) values(31,'笑臉')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid) values(1,'/img/5/573c3e42e71bb874352d1943b697e128bcf08c.jpg','小狐狸','',99,0,1)
insert into tb_tag(wid,tag) values(32,'動物')
insert into tb_tag(wid,tag) values(32,'水彩')
insert into tb_work(mid,picurl,wtitle,winfo,wlike,wissue,aid) values(3,'/img/3/d43f070215e697471429b555efcd22c6.jpg','和服','大和撫子',991,0,3)
insert into tb_tag(wid,tag) values(33,'漫畫')
insert into tb_tag(wid,tag) values(33,'萌')
insert into tb_tag(wid,tag) values(33,'女')
insert into tb_tag(wid,tag) values(33,'日本')
insert into tb_tag(wid,tag) values(33,'花')



